// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "PaxosService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class PaxosServiceHandler : virtual public PaxosServiceIf {
 public:
  PaxosServiceHandler() {
    // Your initialization goes here
  }

  void propose(PaxosProposeResult& _return, const PaxosProposeArgs& pArgs) {
    // Your implementation goes here
    printf("propose\n");
  }

  void accept(PaxosAcceptResult& _return, const PaxosAcceptArgs& aArgs) {
    // Your implementation goes here
    printf("accept\n");
  }

  int64_t getHighestProposalSeen() {
    // Your implementation goes here
    printf("getHighestProposalSeen\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<PaxosServiceHandler> handler(new PaxosServiceHandler());
  shared_ptr<TProcessor> processor(new PaxosServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

