/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Paxos_constants.h"



const PaxosConstants g_Paxos_constants;

PaxosConstants::PaxosConstants() {
}



