/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Paxos_CONSTANTS_H
#define Paxos_CONSTANTS_H

#include "Paxos_types.h"



class PaxosConstants {
 public:
  PaxosConstants();

};

extern const PaxosConstants g_Paxos_constants;



#endif
